services:
  db:
    container_name: hhm_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123@
      POSTGRES_DB: hhmshop
    volumes:
      - ./.docker-data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cache:
    container_name: hhm_cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/cache:/data

  mail-dev:
    container_name: hhm_mail
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  db:
    driver: bridge