services:
  db:
    container_name: hhm_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin123@
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin123@
      MYSQL_DATABASE: hhmshop
    volumes:
      - ./.docker-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cache:
    container_name: hhm_cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/cache:/data

  mail-dev:
    container_name: hhm_mail
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  db:
    driver: bridge