server:
  port: ${PORT:8088}

spring:
  data:
    redis:
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6379}
      password: ${CACHE_PASSWORD:}
      timeout: 15s
      repositories:
        enabled: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hhmshop?useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:admin}
    password: ${MAIL_PASSWORD:Admin123@}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls.enable: ${MAIL_TLS:true}

springdoc:
  api-docs:
    enabled: ${ENABLE_DOC:true}

app:
  active-account-url: ${ACTIVE_ACCOUNT_URL:http://localhost:3306/account/active}

logging:
  level:
    org.springframework.security: DEBUG
