spring:
  application:
    name: hhm-be
  web:
    resources:
      add-mappings: false
  profiles:
    active: ${ENV:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
    time-zone: Asia/Ho_Chi_Minh
  cache:
    type: redis
    redis:
      time-to-live: 60m
    custom-cache:
      user-authority:
        time-to-live: ${ACCESS_TOKEN_EXPIRES_IN:60m}
      invalid-access-token:
        time-to-live: ${ACCESS_TOKEN_EXPIRES_IN:60m}
      invalid-refresh-token:
        time-to-live: ${REFRESH_TOKEN_EXPIRES_IN:1d}
      invalid-refresh-token-long:
        time-to-live: ${REFRESH_TOKEN_LONG_EXPIRES_IN:30d}
      user-otp:
        time-to-live: ${USER_OTP:1m}
  messages:
    encoding: UTF-8
    basename: i18n/messages

springdoc:
  swagger-ui:
    tags-sorter: alpha
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}

security:
  authentication:
    jwt:
      secret-key: ${SECRET_KEY:4B56EB985E5AC77C2D5457AB78D7D2B6D7ECA569D92560FA716E73E57CD9E1746F67D8CEA9663F1022A4DAE1744125D9EC36FF436F5A911420BB576B4817DA43}
      access-token-expires-in: ${ACCESS_TOKEN_EXPIRES_IN:60m}
      refresh-token-expires-in: ${REFRESH_TOKEN_EXPIRES_IN:1d}
      refresh-token-long-expires-in: ${REFRESH_TOKEN_LONG_EXPIRES_IN:30d}

google:
  client-id: 1017906156501-7em9qi30gibuj7lhtpb5k13ts20qrg7s.apps.googleusercontent.com
  client-secret: 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
  redirect-url: http://localhost:8080/api/account/authenticate/callback
  auth-url: https://accounts.google.com/o/oauth2/v2/auth
  token-url: https://oauth2.googleapis.com/token
  user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
  scope: openid%20email%20profile
facebook:
  client-id: 673613752250343
  client-secret: 6d82c600eb888c56a1e5cc987f2e2955
  redirect-url: http://localhost:8080/api/account/authenticate/facebook
  auth-url: https://www.facebook.com/v12.0/dialog/oauth
  token-url: https://graph.facebook.com/v12.0/oauth/access_token
  user-info-url: https://graph.facebook.com/me?fields=id,name,email,picture,first_name,middle_name,last_name,gender
  scope: email%20public_profile

vnpay:
  version: 2.1.0
  tmn-code: Y0ZE5LJM
  hash-secret: N8128FVPMFYYGQFIF9BUNPOP4GJGLKUE
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/payment/vnpay-callback
  expired-time: ${PAYMENT_EXPIRE:1m}

